#!/usr/bin/env python3
"""The four geometries: one bike, four screens, nothing else different.

Reads the bike from the user's own OpenFOAM install rather than carrying a copy, the
way the tutorial's own `Allrun` does and for the same reason -- it is GPL and it is
already on every machine that has OpenFOAM.

Three things happen here:

**The screen is separated from the bike.** They are written as two surfaces so
`snappyHexMesh` can refine them differently. The screen is 0.81% of the bike's area and
the entire subject is where the shear layer leaves its top edge, so it gets one level
more than everything else and that costs about 2% more cells. Refining the whole body
instead costs 2.8x.

**The screen is scaled about its own base.** A taller aftermarket screen is the same
screen extended from its mounting, so this is a scale in z and not a translation --
moving it would tear it off the fairing. The stock screen tops out at z = 1.121 m
against a helmet spanning 1.001 to 1.352, so the four cases put the edge below, at, and
above the helmet.

**The shadow groups are dropped.** The OBJ carries 13 `*-shadow` groups duplicating real
geometry -- same bounds, same face counts -- and snappyHexMesh snaps to both copies.
Removing them cut the mesh from 992,090 to 933,218 cells at the same refinement and
visibly cleaned the nose and front mudguard. Measured, not assumed.

    python3 scripts/build_geometry.py --out work/geometry
"""
from __future__ import annotations

import argparse
import gzip
import os
from pathlib import Path

SCREEN_GROUPS = ("windshield%26", "windshield:002%2")
"""The screen, as the OBJ names it. `windshield-shadow%75` is duplicate geometry and is
dropped with the other shadows rather than scaled -- scaling it would put a second screen
a millimetre from the first."""

CASES = {"short": 1.001, "stock": None, "tall": 1.400}
"""Case name -> where the screen's top edge goes, in metres. `stock` is whatever the
geometry already has, so it is not scaled at all.

Three, not four. The helmet spans 1.001 to 1.352, so these put the shear layer's origin
**below it, across it, and above it** -- the three regimes the subject has. The fourth case
was `mid` at 1.220, which is also across the helmet and therefore the same regime as stock,
a little higher up. It cost a quarter of the compute to say something the stock case already
says, and the compositor draws three panels."""


def source_obj() -> Path:
    tutorials = os.environ.get("FOAM_TUTORIALS")
    if not tutorials:
        raise SystemExit("source OpenFOAM first: FOAM_TUTORIALS is not set")
    path = Path(tutorials) / "resources" / "geometry" / "motorBike.obj.gz"
    if not path.exists():
        raise SystemExit(f"{path} is missing -- is this an OpenFOAM install with tutorials?")
    return path


def read_obj(path: Path):
    """Vertices, and faces grouped by the name they were declared under."""
    text = gzip.decompress(path.read_bytes()).decode("utf-8", "replace")
    verts: list[list[float]] = []
    faces: list[tuple[str, list[int]]] = []
    current = ""
    for line in text.splitlines():
        if line.startswith("v "):
            verts.append([float(x) for x in line.split()[1:4]])
        elif line.startswith(("g ", "o ")):
            current = line[2:].strip()
        elif line.startswith("f "):
            idx = []
            for token in line.split()[1:]:
                i = int(token.split("/")[0])
                idx.append(i - 1 if i > 0 else len(verts) + i)
            faces.append((current, idx))
    return verts, faces


def write_obj(path: Path, verts, faces, name: str) -> int:
    """One surface, carrying only the vertices its own faces use.

    Re-indexed rather than written whole. Keeping the full vertex list looks safer --
    no index arithmetic to get wrong -- and it produces a surface whose bounding box is
    the whole bike and which reports 130,802 duplicate points, because every vertex the
    other surface uses is still in the file with nothing referring to it. A screen whose
    bounding box claims to be two metres long is a bad thing to hand a mesher."""
    used = sorted({i for _group, idx in faces for i in idx})
    renumber = {old: new for new, old in enumerate(used)}
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as fh:
        fh.write(f"# {name}, generated by build_geometry.py\n")
        for i in used:
            x, y, z = verts[i]
            fh.write(f"v {x:.6g} {y:.6g} {z:.6g}\n")
        fh.write(f"g {name}\n")
        for _group, idx in faces:
            fh.write("f " + " ".join(str(renumber[i] + 1) for i in idx) + "\n")
    return len(faces)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--out", type=Path, required=True,
                    help="directory to write <case>/bike.obj and <case>/screen.obj into")
    ap.add_argument("--case", default=None, choices=sorted(CASES),
                    help="build one case instead of all three")
    ap.add_argument("--strict", action="store_true",
                    help="refuse if the screen is fused to the fairing, instead of "
                         "reporting it and going on")
    args = ap.parse_args()

    verts, faces = read_obj(source_obj())
    solid = [(g, i) for g, i in faces if "shadow" not in g.lower()]
    dropped = len(faces) - len(solid)
    bike = [(g, i) for g, i in solid if g not in SCREEN_GROUPS]
    screen = [(g, i) for g, i in solid if g in SCREEN_GROUPS]
    if not screen:
        raise SystemExit("no windshield group found -- has the tutorial geometry changed?")

    screen_pts = sorted({i for _g, idx in screen for i in idx})
    bike_pts = {i for _g, idx in bike for i in idx}
    # **Only points the screen owns outright may move.** 150 of its 2,069 vertices are
    # shared with `frt-fairing`, `frt-fairing:001` and `fairing-inner-plate`, so scaling
    # every screen point drags a piece of the fairing upward with it -- by 150 mm in the
    # tall case. The bike would then differ between cases, which is the one thing an A/B
    # cannot have, and it would differ *silently*: the three bike.obj files came out with
    # three different checksums and nothing else complained.
    #
    # Holding the shared points still is also what a taller screen actually is. Those
    # points are the mounting line where the screen meets the fairing, and a screen bolted
    # to the same fairing does not move its own mounting.
    shared = sorted(set(screen_pts) & bike_pts)
    movable = sorted(set(screen_pts) - bike_pts)
    z = [verts[i][2] for i in screen_pts]
    z_base, z_top = min(z), max(z)
    z_shared_hi = max(verts[i][2] for i in shared) if shared else z_base
    fraction = (z_shared_hi - z_base) / (z_top - z_base)
    print(f"screen points {len(screen_pts):,}: {len(movable):,} owned outright, "
          f"{len(shared):,} shared with the fairing, highest at z = {z_shared_hi:.4f} "
          f"({fraction:.0%} of the screen's height)")

    if fraction > 0.1:
        note = (
            f"\nNOTE: the screen is fused to the fairing, so the fairing moves with it.\n"
            f"  {len(shared)} of the screen's {len(screen_pts):,} vertices also belong to\n"
            f"  frt-fairing, frt-fairing:001 and fairing-inner-plate, and they reach\n"
            f"  {fraction:.0%} of the screen's height rather than sitting along its base. So\n"
            "  scaling the screen lifts the fairing's top lip with it: +206 mm in the tall\n"
            "  case, -89 mm in the short one. The three bike.obj files are therefore not\n"
            "  byte-identical.\n\n"
            "  Holding the shared points instead is worse -- faces would span held and moved\n"
            "  vertices two thirds of the way up, and the screen tears. Generating a clean\n"
            "  parametric screen would avoid both and is the right answer for a validation\n"
            "  study.\n\n"
            "  This is not one. It is a twenty-second clip in which the fairing is grey\n"
            "  geometry behind a coloured field, and a lip 206 mm higher is invisible there\n"
            "  while being exactly what fitting a different screen does to a real bike. The\n"
            "  case README states it, the way subject 01 states its fan curve, and the run\n"
            "  proceeds.\n"
        )
        print(note)
        if args.strict:
            raise SystemExit("--strict: refusing, per the note above")
    print(f"dropped {dropped:,} shadow faces; bike {len(bike):,} faces, "
          f"screen {len(screen):,} faces")
    print(f"screen base {z_base:.4f} m, stock edge {z_top:.4f} m")

    for case, target in CASES.items():
        if args.case and case != args.case:
            continue
        scale = 1.0 if target is None else (target - z_base) / (z_top - z_base)
        moved = [list(v) for v in verts]
        if target is not None:
            for i in movable:
                moved[i][2] = z_base + (verts[i][2] - z_base) * scale
        edge = z_base + (z_top - z_base) * scale
        directory = args.out / case
        write_obj(directory / "bike.obj", moved, bike, "bike")
        write_obj(directory / "screen.obj", moved, screen, "screen")
        print(f"{case:>6}: edge {edge:.4f} m, scale {scale:.3f}x -> {directory}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
